### ISSUE TITLE
QR Code Scan on mobile attendee Check In web page

### ISSUE THREAD

**Issue by neeraj-gulati** [bitpodio/bitpodjs#686]
When attendees come to event venue and bring their email and ticket email or print, we need ability to scan QR code on registration email or on the ticket to change attendee status to checked in. 

Rishi has create a check in webpage added manual check in but there also Scan icon at the bottom for mobile devices. We need to implement QR code scanning and call api to check in the attendee.

here is NPM package for QR scanning, you may check with sukant he sent this but if there is a better out there pls feel free to suggest to sukant. 

https://www.npmjs.com/package/qr-scanner

here is loom of check in page to show you scan button. 

https://drive.google.com/file/d/1CyoSHKJz9W6jFplJwDwuI-bSJPCzIDsE/view?usp=sharing

**Comment by SukantGujar** [comment]
Example https://www.github.com/nimiq/qr-scanner/tree/master/demo%2Findex.html

**Comment by yash-bitpod** [comment]
@SukantGujar I was going through the check-in API on how it works and it requires the `Attendee.id` to check in a particular attendee. Currently the QR code contains the following data in the given format: 
```
Registration Id:${Registration.RegistrationId} ,Event Id:${Event.id} ,Event Name:${Event.Title} ,First Name:${Registration.FullName} ,Email:${Registration.Email}, Mobile: ${Registration.Phone}
``` 
What format should I use to store the `Attendee.id`? Should it just have the `Attendee.id` in the QR code or should it have `Attendee.id` along with other information?

If it should have other information apart from `Attendee.id`, what would be a safe way to parse the string and assure only a normal numeric value goes through? (since this data is user defined)

**Comment by SukantGujar** [comment]
For now just take the values as they are. We would add signature to the generated QR code to prevent tampering.

**Comment by neeraj-gulati** [comment]
AttendeeId and AttendeeName

**Comment by neeraj-gulati** [comment]
Custom api - invalid attendee id validation or already checked In

Toast should be in center and stay there for longer

Disable scan button with message if event has passed its end date.

Show print badge poup/option after checkin if print badge setting is turned on

**Comment by pallaviumap** [comment]
Closed..issues related to enhancement reported on github
