### ISSUE TITLE
Ticket Template:-Mark Name & RTE mandatory and provide alert if null while Add/Edit

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#703]
-Go to Administration ->Ticket template->New ticket template
-Name & RTE is not marked mandatory while Add/Edit but are mandatory.
-For end user he will never know  why "save" is not enabled
-Mark them mandatory and provide alert if the fields are null
![image](https://user-images.githubusercontent.com/83949077/119639518-51367680-be35-11eb-9f96-c17b46d74a35.png)

**Comment by yash-bitpod** [comment]
Resolved with #720

**Comment by pallaviumap** [comment]
![image](https://user-images.githubusercontent.com/83949077/119979887-22f19c00-bfd9-11eb-9ac8-e40bf5fc5f65.png)
New Ticket template option not visible on bitpod ,but visible in other organizations

**Comment by yash-bitpod** [comment]
This is the ticket template selection page for a event not the admin page for ticket template management. You can only create it via the admin view, not the event detail view...

**Comment by pallaviumap** [comment]
It was not visible in admin as well , until I cleared all bitpod related cookies and restarted the system. Anyways that a complete different issue as discussed.
Secondly when i start a fresh form and without entering anything in RTE if I click for couple of time ,the "Save" button get enabled , although the form does not gets saved but the alert as RTE field is mandatory is not displayed
https://www.loom.com/share/97f374f85baa4cdb803470725b584c4d

**Comment by yash-bitpod** [comment]
When you click multiple times on RTE, it adds `HTML` code in the backend as per your clicks. Since templates watch HTML code and not text itself, please verify that the HTML code itself is empty.
![image](https://user-images.githubusercontent.com/74710904/120269436-76a80200-c2c5-11eb-8f38-9c36541299bd.png)
![image](https://user-images.githubusercontent.com/74710904/120269457-80316a00-c2c5-11eb-89f9-3df9c661c08b.png)

**Comment by pallaviumap** [comment]
Got it, will close
