### ISSUE TITLE
Performance issue with Event Details Page

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#733]
The event details page takes forever to load most of the time
1) Load the grid data only when it comes into view.
2) if we reload the page from a grid way down ,then the page should be reloaded with that grid in view

**Comment by yash-bitpod** [comment]
@SukantGujar 

Regarding loading the Grid lazily, I think a solution where we tap into existing `IntersectionObservers` and allowing them to also load for desktop views should allow the grids to load data only when in view. The thing that will need some read up for this scenario is that the current `<Grid>` component uses Apollo Smart Queries, these smart queries officially fetch data automatically on mount. A work-around to skip this behavior and load manually is outlined in: https://github.com/vuejs/vue-apollo/issues/36 but it should require significant testing for reliability since `<Grid>` is a core component.

Coming to point 2: As outlined here: https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router/#scrollbehavior and  https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/router.scrollBehavior.js the default behavior is already set to scroll to previous position on page reload and back. If it isn't working fully, a re-write of this might be needed as well. I suspect this might be due to us loading in all the grids and such on client side itself causing the data-point to be in view on initial load but shift out of it on completing loading.

**Comment by SukantGujar** [comment]
Ok, push this to next release. Start work on it though.

**Comment by yash-bitpod** [comment]
1. Delay the fetch call a fraction of a moment later, so if a user is scrolling down fast, the grids that are skipped past wont pile up the queries.
2. Adjust the dimensions of the initial cards on the Event Board page so that the fetch mode of the grids on top doesn't trigger.

**Comment by pallaviumap** [comment]
-Display the grid only when the title is visible else the loading time on scroll to display the content of the grid is increased ,Also load time for  mid page reload had increased

**Comment by pallaviumap** [comment]
after testing:-
1- it grid loads only if its in view in around 5-6 secs
2-Grid loads even if the title is not visible in around 5-6 secs
3-Top of the page reloads in 5-6 secs with 4-5 images added for banner or others
Could not record loom for this as with loom its takes longer than usual to load
