### ISSUE TITLE
QR Code=>if we go back and forth to check in and back the UI is not appropriate

### ISSUE THREAD

**Issue by pallaviumap** [bitpodio/bitpodjs#868]
-Login to event app
-Go to event with tickets assigned
-Go to check in=>click "<" back to go back to event details page=>go again to check in=>check the UI
-![image](https://user-images.githubusercontent.com/83949077/122523538-c2340d00-d034-11eb-8b87-d81e0036b6dd.png)

**Comment by yash-bitpod** [comment]
As per our discussion, the SPA determines if the user is on mobile or desktop when the site initially loads. If you are on mobile view on initial site load (including a refresh), it will still consider the site to be in mobile view even if you exit to desktop mode until you refresh (re-initialize) the site. Please verify if the bug was caused due to it or another reason.

The above is relevant for #869 as well.

**Comment by pallaviumap** [comment]
Reference the comment in #869
